### ISSUE TITLE
Migrate over fallRunDSM model changes to WR 

### ISSUE THREAD

**Issue by ErinCain** [Reorienting-to-Recovery/winterRunDSM#2]
Migrate over all R2R model updates to this repo winterRunDSM

**Comment by liz-fw** [comment]
in branch `wip`
 
TODO 
- [x] add `r_to_r_baseline_params.R` - confirm updates from fallRun that are migrated to winterRun here
- [x] add `r_to_r_kitchen_sink_params`
- [x] migrate changes from `data.R` ?
- [x] migrate changes from `data-raw/cache-data.R` ?



update harvest logic to be spring instead of fall
look at spring straying approach as well
